### ISSUE TITLE
jats2epub script has inappropriate relative directories

### ISSUE THREAD

**Issue by crism** [eirikhanssen/jats2epub#5]
Script lines like:
```sh
		cp -r assets/epub-template/* output_working/epub/
```
won’t work unless the script is run from its own directory, which means it’s cluttering up its own space with working files. The source files should always be explicitly relative to the script location.

(It would also be nice to specify a working directory, but `CWD` is a reasonable behavior for now.)

**Comment by crism** [comment]
Ah… but the XProc file itself uses relative filenames, causing everything to get written to the `jats2epub` home directory, regardless of where the input file actually was. I think copying the XProc file to the working directory is the way to go; that also allows for future enhancements that involve rewriting the XProc file before running it.

**Comment by eirikhanssen** [comment]
Hello and thank you for your interest in jats2epub.

Indeed, the way I wrote the scripts, the user has to run the script from the folder where it was stored.
I agree that this is not necessarily the best way of doing things. It was a pragmatic solution to get a working tool.

I will take your feedback in account when I do the next update. I don't know when, I might have to wait until the end of August before time allows.

Did you try to create some ePubs using jats2epub yet?

I am curious to hearing about your experiences.

**Comment by eirikhanssen** [comment]
I pulled inn your suggestions and put it in a new issue3 branch, so I can review it later when I have time.
You can safely close the pull request now.

Thanks for the feedback.

**Comment by crism** [comment]
Thanks, Eirik. I just committed some more changes to address these relative path issues. I only changed the UNIX side of the world; Windows batch scripts will need analogous changes.
